package demo.cartpromofact;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CartEntry implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer qty;
   private java.lang.Double price;

   private demo.cartpromofact.Product product;

   public CartEntry()
   {
   }

   public java.lang.Integer getQty()
   {
      return this.qty;
   }

   public void setQty(java.lang.Integer qty)
   {
      this.qty = qty;
   }

   public java.lang.Double getPrice()
   {
      return this.price;
   }

   public void setPrice(java.lang.Double price)
   {
      this.price = price;
   }

   public demo.cartpromofact.Product getProduct()
   {
      return this.product;
   }

   public void setProduct(demo.cartpromofact.Product product)
   {
      this.product = product;
   }

   public CartEntry(java.lang.Integer qty, java.lang.Double price,
         demo.cartpromofact.Product product)
   {
      this.qty = qty;
      this.price = price;
      this.product = product;
   }

}