package demo.cartpromofact;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Product implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String id;

   public Product()
   {
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public Product(java.lang.String id)
   {
      this.id = id;
   }

}