package demo.cartpromofact;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class User implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String name;

   public User()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public User(java.lang.String name)
   {
      this.name = name;
   }

}